### ISSUE TITLE
Optimized incremental aggregation for linear incremental functions.

### ISSUE THREAD

**Issue by ryzhyk** [vmware/database-stream-processor#74] opened 2022-06-01 22:27 UTC
### Is your feature request related to a problem? Please describe.

Linear aggregates can be computed incrementally.  Converting the output of a linear aggregate to a Z-set in unfortunately no longer linear. Question is whether there's anything useful we can do with regular sets or perhaps with Z-sets with non-standard weights (since the output of a linear aggregate can be modeled as a Z-set whose weight type is the value of the aggregate).  If so, we can expose the purely linear aggregation API; otherwise, it will have to bundled with Z-set conversion.

### Describe the solution you'd like

-

**Comment by mbudiu-vmw** [comment] 2023-01-12 17:24
This is a duplicate of #138

**Closed by mbudiu-vmw** 2023-01-12 17:24 UTC
Labels: enhancement

**Comment by ryzhyk** [comment] 2023-01-12 17:52
It's not really a duplicate, but I'm ok with closing it, as I don't plan to work on this (not sure this is a real issue or what can be done about it)
